spring:
  application:
    name: auth-service

  datasource:
    url: {DB_DATASOURCE_URL}
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: auth-db-connection-pool
      leak-detection-threshold: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: {REDIS_HOST}
      port: {REDIS_PORT}
      database: {REDIS_DATABASE_INDEX}
      jedis:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          max-wait: -1m
          min-idle: 0
          time-between-eviction-runs: 200ms

auth:
  security:
    brute-force:
      login:
        max-attempts: 5
        ban-duration-minutes: 15
        user-attempt-key-prefix: LOGIN_FAILED_ATTEMPT_USER_
        user-block-key-prefix: LOGIN_BLOCKED_USER_
        ip-attempt-key-prefix: LOGIN_FAILED_ATTEMPT_IP_
        ip-block-key-prefix: LOGIN_BLOCKED_IP_
      register:
        max-attempts: 5
        ban-duration-minutes: 15
        ip-attempt-key-prefix: REGISTER_FAILED_ATTEMPT_IP_
        ip-block-key-prefix: REGISTER_BLOCKED_IP_

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

token:
  access-token-expiry-hours: 1
  refresh-token-expiry-hours: 72
  access-token-issuer: http://localhost:8081
  access-token-claim-type: access_token
  refresh-token-issuer: http://localhost:8081
  refresh-token-claim-type: refresh_token

logging:
  level:
    root: warn
    com.mhs.com.mhs.authService: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.springframework.jdbc.datasource.DataSourceTransactionManager: info