server:
  port: 8080

spring:
  application:
    name: auth-service
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10           # Default: 10
      minimum-idle: 2                 # Default: same as max
      connection-timeout: 5000         # 5 seconds (default)
      idle-timeout: 600000             # 10 minutes (default)
      max-lifetime: 1800000            # 30 minutes (default)
      pool-name: auth-db-connection-pool
      leak-detection-threshold: 10000  # 10 seconds (optional)
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      jedis:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          max-wait: -1m
          min-idle: 0
          time-between-eviction-runs: 200ms

auth:
  security:
    brute-force:
      login:
        max-attempts: 5
        ban-duration-minutes: 15
        user-attempt-key-prefix: LOGIN_FAILED_ATTEMPT_USER_
        user-block-key-prefix: LOGIN_BLOCKED_USER_
        ip-attempt-key-prefix: LOGIN_FAILED_ATTEMPT_IP_
        ip-block-key-prefix: LOGIN_BLOCKED_IP_
      register:
        max-attempts: 5
        ban-duration-minutes: 15
        ip-attempt-key-prefix: REGISTER_FAILED_ATTEMPT_IP_
        ip-block-key-prefix: REGISTER_BLOCKED_IP_

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

token:
  access-token-expiry-hours: 1
  refresh-token-expiry-hours: 72
  access-token-issuer: http://localhost:8081
  access-token-claim-type: access_token
  refresh-token-issuer: http://localhost:8081
  refresh-token-claim-type: refresh_token

logging:
  level:
    root: INFO
    com.mhs.com.mhs.authService: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.springframework.jdbc.datasource.DataSourceTransactionManager: info